-- ============================================================
-- NEW SUPABASE PROJECT INITIAL SCHEMA
-- Target project: nvcxaddealeuvttvzrsa
-- Run this in Supabase SQL Editor for the new project.
-- ============================================================

-- ─── Enable extensions ────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── deals ───────────────────────────────────────────────────────────────────
-- Full final schema after all migrations (no legacy columns)
CREATE TABLE IF NOT EXISTS public.deals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NULL,
  price double precision NULL,
  currency text NULL,
  link text NULL,
  booking_url text NULL,
  skyscanner_url text NULL,
  source text NULL,
  origin text NULL,
  destination text NULL,
  origin_iata text NULL,
  destination_iata text NULL,
  airline text NULL,
  aircraft text NULL,
  cabin_class text NULL,
  stops integer NULL,
  date_out date NULL,
  date_in date NULL,
  miles text NULL,
  flight_duration_minutes integer NULL,
  flight_duration_display text NULL,
  baggage_included boolean NULL,
  baggage_pieces_included smallint NULL,
  baggage_allowance_kg integer NULL,
  image text NULL,
  tier text NULL DEFAULT 'free',
  travel_period_display text NULL,
  scoring text NULL,
  expires_in text NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_booking_url_key UNIQUE (booking_url)
) TABLESPACE pg_default;

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS deals_source_idx ON public.deals (source);
CREATE INDEX IF NOT EXISTS deals_tier_idx ON public.deals (tier);
CREATE INDEX IF NOT EXISTS deals_origin_iata_idx ON public.deals (origin_iata);
CREATE INDEX IF NOT EXISTS deals_destination_iata_idx ON public.deals (destination_iata);
CREATE INDEX IF NOT EXISTS deals_cabin_class_idx ON public.deals (cabin_class);
CREATE INDEX IF NOT EXISTS deals_stops_idx ON public.deals (stops);
CREATE INDEX IF NOT EXISTS deals_source_date_out_idx ON public.deals (source, date_out);
CREATE INDEX IF NOT EXISTS deals_scoring_idx ON public.deals (scoring);

-- RLS: anon can read deals (frontend display)
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon can read deals" ON public.deals FOR SELECT TO anon USING (true);
CREATE POLICY "auth can read deals" ON public.deals FOR SELECT TO authenticated USING (true);
-- Backend writes via service_role key (bypasses RLS) — no client insert policy needed

-- ─── source_articles ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.source_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  article_url text NOT NULL,
  first_seen_at timestamp with time zone NULL DEFAULT now(),
  last_scraped_at timestamp with time zone NULL,
  status text NULL DEFAULT 'pending',
  source text NULL,
  last_error text NULL,
  CONSTRAINT source_articles_pkey PRIMARY KEY (id),
  CONSTRAINT source_articles_article_url_key UNIQUE (article_url)
) TABLESPACE pg_default;

ALTER TABLE public.source_articles ENABLE ROW LEVEL SECURITY;
-- No client-facing policies — backend only via service_role

-- ─── subscribers ─────────────────────────────────────────────────────────────
CREATE TYPE IF NOT EXISTS public.subscriber_status AS ENUM ('pending', 'active', 'unsubscribed');

CREATE TABLE IF NOT EXISTS public.subscribers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  status public.subscriber_status NOT NULL DEFAULT 'pending',
  tier text NOT NULL DEFAULT 'free',
  source text NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;
-- Anon can INSERT (newsletter signup from landing page)
CREATE POLICY "subscribers_insert_anon" ON public.subscribers
  FOR INSERT TO anon WITH CHECK (true);
-- No SELECT/UPDATE/DELETE for anon or authenticated clients
-- Edge functions use service_role key for all reads/writes

-- ─── waitlist ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.waitlist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  location text NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "waitlist_insert_anon" ON public.waitlist
  FOR INSERT TO anon WITH CHECK (true);

-- ─── payments ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  amount_cents integer NULL,
  currency text NOT NULL DEFAULT 'CHF',
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
-- Completely locked — service_role only
CREATE POLICY "payments_no_select_anon" ON public.payments FOR SELECT TO anon USING (false);
CREATE POLICY "payments_no_select_auth" ON public.payments FOR SELECT TO authenticated USING (false);
CREATE POLICY "payments_no_insert_anon" ON public.payments FOR INSERT TO anon WITH CHECK (false);
CREATE POLICY "payments_no_insert_auth" ON public.payments FOR INSERT TO authenticated WITH CHECK (false);
CREATE POLICY "payments_no_update_auth" ON public.payments FOR UPDATE TO authenticated USING (false);
CREATE POLICY "payments_no_delete_auth" ON public.payments FOR DELETE TO authenticated USING (false);

-- Helper function for pending payment insert (called from edge function via service_role)
CREATE OR REPLACE FUNCTION public.insert_payment_pending(p_email text)
RETURNS public.payments AS $$
  INSERT INTO public.payments (email, status, currency)
  VALUES (p_email, 'pending', 'CHF')
  ON CONFLICT DO NOTHING
  RETURNING *;
$$ LANGUAGE sql SECURITY DEFINER;

-- ─── user_preferences ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_preferences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  email text NOT NULL,
  -- Departure airports (ZRH, GVA, BSL)
  preferred_origins text[] DEFAULT ARRAY['ZRH'],
  -- Destination regions: 'europe','americas','asia_pacific','middle_east','africa','oceania'
  preferred_regions text[] DEFAULT ARRAY[]::text[],
  -- Budget max CHF per person (NULL = no limit)
  max_price_chf integer DEFAULT NULL,
  -- Cabin class: 'Economy', 'Business', 'First', 'Premium Economy'
  cabin_classes text[] DEFAULT ARRAY['Economy'],
  -- Trip duration (days)
  min_trip_days integer DEFAULT 2,
  max_trip_days integer DEFAULT NULL,
  -- Travel timing: 'summer','winter','spring_fall','any'
  preferred_seasons text[] DEFAULT ARRAY['any'],
  -- Flight type: 'short_haul','long_haul'
  flight_types text[] DEFAULT ARRAY['short_haul','long_haul'],
  -- Content toggles
  include_miles_deals boolean DEFAULT true,
  include_budget_deals boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
-- Authenticated users can only manage their own preferences row
CREATE POLICY "user_preferences_own_row" ON public.user_preferences
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Index for fast lookup by user_id
CREATE INDEX IF NOT EXISTS user_preferences_user_id_idx ON public.user_preferences (user_id);
CREATE INDEX IF NOT EXISTS user_preferences_email_idx ON public.user_preferences (email);

-- ─── Trigger: auto-update updated_at ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER subscribers_updated_at
  BEFORE UPDATE ON public.subscribers
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER user_preferences_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER waitlist_updated_at
  BEFORE UPDATE ON public.waitlist
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
