-- Adds the deals pipeline tables to the unified Supabase project.
-- Run this in Supabase SQL Editor for project wwoowwnjrepokmjgxhlw.

-- ─── deals ───────────────────────────────────────────────────────────────────
create table if not exists public.deals (
  id bigint generated by default as identity not null,
  title text null,
  price double precision null,
  link text null,
  currency text null,
  image text null,
  cabin_baggage text null,
  aircraft text null,
  airline text null,
  origin text null,
  destination text null,
  miles text null,
  expires_in text null,
  booking_url text null,
  date_in date null,
  date_out date null,
  cabin_class text null,
  one_way boolean null,
  flight text null,
  origin_iata text null,
  destination_iata text null,
  date_range text null,
  source text null,
  scoring text null,
  flight_duration_minutes integer null,
  flight_duration_display text null,
  baggage_included boolean null,
  baggage_pieces_included smallint null,
  baggage_allowance_kg integer null,
  baggage_allowance_display text null,
  llm_enriched boolean null,
  llm_enriched_fields jsonb null,
  llm_enrichment_version text null,
  created_at timestamp with time zone default now(),
  constraint deals_pkey primary key (id),
  constraint deals_booking_url_key unique (booking_url)
) tablespace pg_default;

-- ─── source_articles ─────────────────────────────────────────────────────────
create table if not exists public.source_articles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  article_url text not null,
  first_seen_at timestamp with time zone null default now(),
  last_scraped_at timestamp with time zone null,
  status text null default 'pending'::text,
  source text null,
  last_error text null,
  constraint source_articles_pkey primary key (id),
  constraint source_articles_article_url_key unique (article_url)
) tablespace pg_default;

-- ─── RLS ─────────────────────────────────────────────────────────────────────
alter table public.deals enable row level security;
alter table public.source_articles enable row level security;

-- Allow anonymous users to read deals (for future frontend display)
create policy "anon can read deals"
  on public.deals for select
  to anon
  using (true);

-- Backend writes deals using the service_role key, which bypasses RLS.
-- No explicit insert/update policy needed for anon on these tables.
